version: '3.8'

services:
  
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: document_store
      MYSQL_USER: phuc
      MYSQL_PASSWORD: phuc
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
